### ISSUE TITLE
The new iamRole field should be encrypted

### ISSUE THREAD

**Issue by jkurz** [turnerlabs/shipit-api#42]
* we need to encrypt the iamRole field on PUT and POST
* we need to decrypt the iamRole field on GET

**Comment by jkurz** [comment]
Maybe we could just get away with hiding the values with **** if the user is not authorized to view the content. Now that we have many factors to the DB, it's much more secure and doesn't necessarily require encryption for this field. Thoughts?

**Comment by wilsonodk** [comment]
I'm thinking that `****` is good for now.

**Comment by jkurz** [comment]
This can be closed. We already implemented this logic in https://github.com/turnerlabs/shipit-api/commit/8e185c9936954ef8d7ccdd92ba64965f751843a6
